[package]
  cjc-version = "1.1.0"
  name = "zmq4cj_bench"
  organization = ""
  description = "ZeroMQ Cangjie bindings benchmark"
  version = "1.0.0"
  output-type = "executable"

[dependencies]
  zmq4cj = { path = "../" }

[target.x86_64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.x86_64-unknown-linux-gnu.ffi.c]
zmq = { path = "../vendor/build/linux/lib" }

[target.aarch64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.aarch64-unknown-linux-gnu.ffi.c]
zmq = { path = "../vendor/build/linux/lib" }

[target.x86_64-apple-darwin]
  link-option = "-lc++"

[target.x86_64-apple-darwin.ffi.c]
zmq = { path = "../vendor/build/darwin/lib" }

[target.aarch64-apple-darwin]
  link-option = "-lc++"

[target.aarch64-apple-darwin.ffi.c]
zmq = { path = "../vendor/build/darwin/lib" }
