[package]
  cjc-version = "1.1.0"
  name = "zmq4cj"
  organization = ""
  description = "ZeroMQ bindings for Cangjie"
  version = "1.0.0"
  target-dir = ""
  script-dir = ""
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[target.x86_64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.x86_64-unknown-linux-gnu.ffi.c]
zmq = { path = "vendor/build/linux/lib" }

[target.aarch64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.aarch64-unknown-linux-gnu.ffi.c]
zmq = { path = "vendor/build/linux/lib" }

[target.x86_64-apple-darwin]
  link-option = "-lc++"

[target.x86_64-apple-darwin.ffi.c]
zmq = { path = "vendor/build/darwin/lib" }

[target.aarch64-apple-darwin]
  link-option = "-lc++"

[target.aarch64-apple-darwin.ffi.c]
zmq = { path = "vendor/build/darwin/lib" }

[target.x86_64-w64-mingw32]
  link-option = "-lstdc++ -lgcc -lws2_32 -liphlpapi"

[target.x86_64-w64-mingw32.ffi.c]
zmq = { path = "vendor/build/windows/lib" }
