[package]
  cjc-version = "1.1.0"
  name = "zmq"
  organization = ""
  description = "ZeroMQ bindings for Cangjie"
  version = "0.0.1"
  output-type = "static"
  repository = "https://github.com/gtn1024/zmq4cj"
  license = ["MIT"]
  tag = ["zeromq", "zmq", "network", "messaging"]
  category = ["Network"]
  include = ["src", "build.cj", "vendor/libzmq"]
  exclude = ["vendor/build"]

[dependencies]

[target.x86_64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.x86_64-unknown-linux-gnu.ffi.c]
zmq_vendor = { path = "vendor/build/linux/lib" }

[target.aarch64-unknown-linux-gnu]
  link-option = "-lstdc++ -lgcc_s"

[target.aarch64-unknown-linux-gnu.ffi.c]
zmq_vendor = { path = "vendor/build/linux/lib" }

[target.x86_64-apple-darwin]
  link-option = "-lc++"

[target.x86_64-apple-darwin.ffi.c]
zmq_vendor = { path = "vendor/build/darwin/lib" }

[target.aarch64-apple-darwin]
  link-option = "-lc++"

[target.aarch64-apple-darwin.ffi.c]
zmq_vendor = { path = "vendor/build/darwin/lib" }

